
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: setingup node js
      uses: actions/setup_node@v2-beta
      with:
        version:  12
    - name: npm install is runnig
      run: npm install
    - name: react is building
      run: npm build
    - name: surge is running
      run: surge ./build http://umarkhan_uk_react.surge.sh/ --token ${{secrets.REACT_SURGE_TOKEN}}
